### PR TITLE
TEMP FIX: How To fix for SD models not working on v2.0 docker.

### PR DESCRIPTION
**Pull request by lunamidori5**
**Description**

This PR fixes: Nothing for now, but I have had a few messages on discord about it

**Notes for Reviewers**
This is a temp fix, will fully remake the page when I know everything is working and updated! <3

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by lunamidori5** [comment]
@mudler

**Comment by lunamidori5** [comment]
@mudler or @dave-gray101 this needs merged so I can get the remake started when you get time <3

**Comment by mudler** [comment]
@lunamidori5 I think it's better to have it fixed properly, as this now would be just confusing (as it removes examples of how to use SDXL and replaces them with standard SD)

**Comment by mudler** [comment]
SDXL now should be working too, there is actually no need to specify a PipelineType anymore

**Comment by mudler** [comment]
it is in the docs: https://localai.io/model-compatibility/diffusers/#model-setup

**Pull request closed without merging**
