### PR TITLE
docs/examples: enhancements

### PR DESCRIPTION
**Pull request by mudler**
**Description**

Related to #1373, as this is still an effort of ease usage. This is also a follow-up of https://github.com/mudler/LocalAI/pull/1556. I'm planning to add missing examples here. 

For models, I think it's a good metric what I've seen in https://twitter.com/gblazex/status/1744602366798594150 - so I'll add the models for those in that list.

Fixes https://github.com/mudler/LocalAI/issues/1561. Related to: #1373 #1031 #1416

**Notes for Reviewers**

Also adds documentation around https://github.com/mudler/LocalAI/issues/1561

cc @chris-hatton @apstrom 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by mudler** [comment]
Currently evaluating if switching docs to https://lotusdocs.dev/docs/quickstart/ or https://amethyst.bencuan.me/

**Comment by mudler** [comment]
cc @chris-hatton @apstrom I'd be happy (and would be really appreciated) to get your thoughts in here once this is ready for review

**Comment by apstrom** [comment]
> cc @chris-hatton @apstrom I'd be happy (and would be really appreciated) to get your thoughts in here once this is ready for review

I am more than happy to help. I am using LocalAI as a base to set up my firm's in-house LLMs and GPTs. When I have time, I can help draft some of these documents to explain things like YAML configuration, initial setup, etc.

**Comment by lunamidori5** [comment]
@mudler on the quickstart page, I have made a program that both sets up the docker image, and sets up a model, if you want to put that at the top somewhere under docker desktop.

https://io.midori-ai.xyz/howtos/easy-localai-installer/
https://io.midori-ai.xyz/howtos/easy-model-installer/

Both are super easy to run on OS like Windows and does all of the work for the end user!

**Comment by lunamidori5** [comment]
Or we could make a intergr page for them

**Comment by mudler** [comment]
ready to merge, and it already took enough of my time :) changes to it can be done later on!

**Pull request merged**
