### PR TITLE
feat: add tiny dream stable diffusion support

### PR DESCRIPTION
**Pull request by M0Rf30**
**Description**

This PR adds backend support for tiny dream
[An embedded, Header Only, Stable Diffusion Inference C++ Library](https://github.com/symisc/tiny-dream#tiny-dreaman-embedded-header-only-stable-diffusion-inference-c-librarypixlabiotiny-dream)

This means that we can run a stable diffusion model without the issues on opencv2 or abseil dependencies.
 Two companion repos appeared:
 https://github.com/M0Rf30/go-tiny-dream
 https://github.com/M0Rf30/tiny-dream-bins for model bins (they are the same as stable diffusion, the company asks for money on models, maybe I can patch the .hpp at build time and avoid waste of space?) 
  
**Notes for Reviewers**
Here the model https://github.com/go-skynet/model-gallery/pull/47

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by mudler** [comment]
I like it !  however it is better if it waits for https://github.com/mudler/LocalAI/pull/1279 - the PR is moving backends to the new folder structure to clean things up a bit after the new backend changes, and as soon as is it's green should be merged already

**Comment by M0Rf30** [comment]
I rebased on master. need only to spot this one remaining issue on failing linux test in ci

**Review by mudler — DISMISSED** [review]
looking good here, just waiting for CI to pass - thanks @M0Rf30 for taking the extra effort of adding tests for it!

**Comment by M0Rf30** [comment]
> looking good here, just waiting for CI to pass - thanks @M0Rf30 for taking the extra effort of adding tests for it!

Merge of this 
https://github.com/go-skynet/model-gallery/pull/51
should also fix linux tests

**Comment by M0Rf30** [comment]
> from the logs it looks like we exhaust the machine's resources. Public runners don't have big specs, maybe we can keep the test separated or try to run _only that one_ in the self-hosted runners? @M0Rf30

Seems fair to me. I rebase and push

**Comment by M0Rf30** [comment]
Tests live here
https://github.com/mudler/LocalAI/pull/1410

I don't know how to choose between self-hosted and public instances so I made two different commits

**Comment by M0Rf30** [comment]
@mudler  merry christmas. now is ready to go.

**Comment by mudler** [comment]
> @mudler merry christmas. now is ready to go.

merry xmas to you too @M0Rf30 !

**Review by mudler — APPROVED** [review]

**Pull request merged**
