### PR TITLE
Revert "feat: include tokens usage for streamed output"

### PR DESCRIPTION
**Pull request by mudler**
Reverts mudler/LocalAI#4282

See: https://github.com/mudler/LocalAI/issues/4334

### CODE REVIEW

**Comment by mudler** [comment]
ping @mintyleaf - seems the changeset blocks the server from serving further requests, I'm going to revert and tag a patch release until you can provide a fix quicker than me :)

**Comment by mintyleaf** [comment]
> ping @mintyleaf - seems the changeset blocks the server from serving further requests, I'm going to revert and tag a patch release until you can provide a fix quicker than me :)

really strange, bc i tested it locally on that examplish small phi2 model on arm64 mac and there is no issues with multiple requests to it 

you really sure that my changeset causing this / able to reproduce that behavior?

**Comment by mudler** [comment]
> > ping @mintyleaf - seems the changeset blocks the server from serving further requests, I'm going to revert and tag a patch release until you can provide a fix quicker than me :)
> 
> really strange, bc i tested it locally on that examplish small phi2 model on arm64 mac and there is no issues with multiple requests to it
> 
> you really sure that my changeset causing this / able to reproduce that behavior?

yep tested myself and was able to reproduce the behavior, reverting the changeset fixed it here. I've tested directly in the LocalAI WebUI

**Comment by mintyleaf** [comment]
> > > ping @mintyleaf - seems the changeset blocks the server from serving further requests, I'm going to revert and tag a patch release until you can provide a fix quicker than me :)
> > 
> > 
> > really strange, bc i tested it locally on that examplish small phi2 model on arm64 mac and there is no issues with multiple requests to it
> > you really sure that my changeset causing this / able to reproduce that behavior?
> 
> yep tested myself and was able to reproduce the behavior, reverting this changeset fixed it here. I've tested directly in the LocalAI WebUI: to reproduce you have to run subsequent messages in the chat and it will stall indefinetly

can you say which model you used?
still can't reproduce that web ui behavior with phi-2.Q2_K

**Pull request merged**
