### PR TITLE
feat: tokenization endpoint

### PR DESCRIPTION
**Pull request by shraddhazpy**
**Description**

This PR is a step towards #1649 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by shraddhazpy** [comment]
@mudler Guessing that this would need work on the cpp side as well to get the tokenization going there too.

**Comment by mudler** [comment]
> @mudler Guessing that this would need work on the cpp side as well to get the tokenization going there too.

Correct, we basically need to expose https://github.com/mudler/LocalAI/blob/44bdacac61a319992f3bf3a32f756a65862617ed/backend/cpp/llama/grpc-server.cpp#L549 as a gRPC method, but it would make sense also to do it afterwards :+1: - thanks for the PR!

**Comment by mudler** [comment]
@shraddhazpy I need the commits signed off (you can do that with `git rebase origin/master --signoff`) in order to merge the PR

**Review by mudler — APPROVED** [review]
Looking good!

**Pull request merged**
