### PR TITLE
Update Makefile to support MOE

### LINKED ISSUE #1421: Mixtral support ?
I would like to ask (if not already planned) to support Mixtral from MistralAI 

https://docs.mistral.ai/models/

Thank you

### PR DESCRIPTION
**Pull request by sfxworks**
In reference to https://github.com/ggerganov/llama.cpp/pull/4406

Need a newer version of llama.cpp to handle MoE models, such as Mixtral 8x7b

**Description**

This PR fixes #1421

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sfxworks** [comment]
Currently building and testing locally to confirm it works.

Using
```yaml
#backend: llama
context_size: 8192
f16: true
low_vram: false
gpu_layers: 98
mmlock: false
name: mixtral
parameters:
  model: mixtral-8x7b-v0.1.Q4_K_M.gguf
  temperature: 0.2
```

**Comment by sfxworks** [comment]
```
I local-ai build info:
I BUILD_TYPE: hipblas
I GO_TAGS: 
I LD_FLAGS: -X "github.com/go-skynet/LocalAI/internal.Version=v2.0.0" -X "github.com/go-skynet/LocalAI/internal.Commit=238fec244ae6c9a66bc7fafd76c7e14671110a6f"
CGO_LDFLAGS="-L/opt/rocm/hip/lib -lamdhip64 -L/opt/rocm/lib -lOpenCL -L/usr/lib -lclblast -lrocblas -lhipblas -lrocrand -lomp -O3 --rtlib=compiler-rt -unwindlib=libgcc -lhipblas -lrocblas --hip-link -O3 --rtlib=compiler-rt -unwindlib=libgcc -lhipblas -lrocblas --hip-link" go build -ldflags "-X "github.com/go-skynet/LocalAI/internal.Version=v2.0.0" -X "github.com/go-skynet/LocalAI/internal.Commit=238fec244ae6c9a66bc7fafd76c7e14671110a6f"" -tags "" -o local-ai ./
```

```
10:02AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:42533): stderr error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found
```

Hmm, that doesn't appear to be where to change it.

**Comment by sfxworks** [comment]
Maybe gollama needs to be updated as well?

**Comment by sfxworks** [comment]
Tried with

```
GOLLAMA_VERSION?=77e691050c5401f03240f1960410e286fb50e8e2
CPPLLAMA_VERSION?=cafcd4f89500b8afef722cdb08088eceb8a22572
```
To reflect upstream update attempt https://github.com/go-skynet/go-llama.cpp/pull/313 but failed

```
cd llama.cpp && patch -p1 < ../patches/1902-cuda.patch
patching file common/common.cpp
Hunk #1 succeeded at 1614 with fuzz 2 (offset 346 lines).
patching file common/common.h
Hunk #1 FAILED at 209.
1 out of 1 hunk FAILED -- saving rejects to file common/common.h.rej
make[1]: *** [Makefile:235: prepare] Error 1
make[1]: Leaving directory '/home/sam/LocalAI/sources/go-llama'
make: *** [Makefile:223: sources/go-llama/libbinding.a] Error 2
```

**Comment by sfxworks** [comment]
seems to be the same issue in their CI https://github.com/go-skynet/go-llama.cpp/actions/runs/7212854485/job/19651445657?pr=313

**Comment by sfxworks** [comment]
Trying against https://github.com/go-skynet/go-llama.cpp/pull/315

**Comment by sfxworks** [comment]
hmm

```
11:03AM DBG GRPC: Loading model with options: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Model:mixtral-8x7b-v0.1.Q4_K_M.gguf ContextSize:8192 Seed:0 NBatch:512 F16Memory:true MLock:false MMap:false VocabOnly:false LowVRAM:false Embeddings:false NUMA:false NGPULayers:98 MainGPU: TensorSplit: Threads:4 LibrarySearchPath:/tmp/localai/backend_data/backend-assets/gpt4all RopeFreqBase:0 RopeFreqScale:0 RMSNormEps:0 NGQA:0 ModelFile:/home/sam/LocalAI/models/mixtral-8x7b-v0.1.Q4_K_M.gguf Device: UseTriton:false ModelBaseName: UseFastTokenizer:false PipelineType: SchedulerType: CUDA:false CFGScale:0 IMG2IMG:false CLIPModel: CLIPSubfolder: CLIPSkip:0 Tokenizer: LoraBase: LoraAdapter: LoraScale:0 NoMulMatQ:false DraftModel: AudioPath: Quantization: MMProj: RopeScaling: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0}
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr 
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr /home/sam/LocalAI/sources/go-rwkv/rwkv.cpp/rwkv.cpp:250: header.magic == 0x67676d66
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr Invalid file header
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr /home/sam/LocalAI/sources/go-rwkv/rwkv.cpp/rwkv.cpp:1132: rwkv_fread_file_header(file.file, model.header)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr 
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr /home/sam/LocalAI/sources/go-rwkv/rwkv.cpp/rwkv.cpp:1266: rwkv_instance_from_file(file_path, *instance.get())
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr panic: runtime error: invalid memory address or nil pointer dereference
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa9b0ce]
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr 
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr goroutine 19 [running]:
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr github.com/donomii/go-rwkv%2ecpp.LoadFiles.(*Context).GetStateBufferElementCount.func1(0xc000232040?)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/sources/go-rwkv/wrapper.go:63 +0xe
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr github.com/donomii/go-rwkv%2ecpp.(*Context).GetStateBufferElementCount(...)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/sources/go-rwkv/wrapper.go:63
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr github.com/donomii/go-rwkv%2ecpp.LoadFiles({0xc000232040?, 0xc000232059?}, {0xc000230050, 0x45}, 0xa7e486?)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/sources/go-rwkv/wrapper.go:131 +0x52
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr main.(*LLM).Load(0xc00002ecd0, 0xc000246000)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/backend/go/llm/rwkv/rwkv.go:31 +0xee
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr github.com/go-skynet/LocalAI/pkg/grpc.(*server).LoadModel(0xc00002eda0, {0xc000246000?, 0x793b06?}, 0x0?)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/pkg/grpc/server.go:50 +0xe6
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr github.com/go-skynet/LocalAI/pkg/grpc/proto._Backend_LoadModel_Handler({0x2c8000?, 0xc00002eda0}, {0x3ae5f0, 0xc00020e360}, 0xc000214100, 0x0)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/LocalAI/pkg/grpc/proto/backend_grpc.pb.go:264 +0x169
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002dc1e0, {0x3ae5f0, 0xc00020e2a0}, {0x3b1758, 0xc0003a6000}, 0xc00023c000, 0xc0002e2cc0, 0xaf6b90, 0x0)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr google.golang.org/grpc.(*Server).handleStream(0xc0002dc1e0, {0x3b1758, 0xc0003a6000}, 0xc00023c000)
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr google.golang.org/grpc.(*Server).serveStreams.func1.1()
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 36
11:03AM DBG GRPC(mixtral-8x7b-v0.1.Q4_K_M.gguf-127.0.0.1:34967): stderr         /home/sam/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145
```

**Comment by mudler** [comment]
did you tried with the `llama-cpp` backend?

**Comment by sfxworks** [comment]
> did you tried with the `llama-cpp` backend? It should also be the default

I tried both with backend: llama commented and uncomment. No success. The last comment was with it uncommented.

**Comment by mudler** [comment]
did you tried without acceleration too?

**Comment by sfxworks** [comment]
Didn't try this model without acceleration, but I did try another model with acceleration and it worked just fine.

**Comment by mudler** [comment]
maybe it is an upstream issue, the llama-cpp backend is the most close to upstream one, if that fails something might be off with llama.cpp. master just got latest hash in https://github.com/mudler/LocalAI/pull/1429, I'll try to give it a go later today too

**Comment by sfxworks** [comment]
I'll give that a try today

**Comment by mudler** [comment]
Tried today and works locally, adding a full example in https://github.com/mudler/LocalAI/pull/1449

**Comment by mudler** [comment]
@sfxworks appreciate the effort here, but I think we can close this one as we have more up-to-date hashes in master, or is there anything pending? did you tried if mixtral works for you?

**Comment by sfxworks** [comment]
Yep! All works I appreciate it!

**Pull request closed without merging**
