### PR TITLE
Git fetch specific branch instead of full tree during build

### PR DESCRIPTION
**Pull request by LoricOSC**
**Description**

This PR fixes # N/A

**Notes for Reviewers**
This change only pulls the needed branch instead of the whole tree.  make prepare is roughly 1/2 the size.

### CODE REVIEW

**Review by mudler — APPROVED** [review]
much appreciated, thank you!

**Review by dave-gray101 — DISMISSED** [review]
quickly patching the makefile before the bot eats it again 😅

**Comment by LoricOSC** [comment]
I realized this will break any automation attached to updating the llama go release.  I can change it back to include the STABLE if needed.

**Comment by mudler** [comment]
> I realized this will break any automation attached to updating the llama go release. I can change it back to include the STABLE if needed.

just checked - shouldn't break but if something does it's trivial ( workflow is here: https://github.com/mudler/LocalAI/blob/b6b8ab6c219415576431649bcb9999e1f2e0ef22/.github/workflows/bump_deps.yaml#L12 )

**Comment by dave-gray101** [comment]
@LoricOSC looks like you forgot to signoff your commits. If you get a chance, can you amend those?

@mudler - do we _actually_ care about DCO enough to block on this? If this passes all tests, should we just bypass the check rather than wait for amendment? While I've reviewed the changes, it's not "best practice" for me to just sign over them all, I assume 😆

**Review by dave-gray101 — APPROVED** [review]

**Pull request merged**
