### PR TITLE
feat(conda): conda environments

### LINKED ISSUE #1117: enhancement: use separate conda env for extra grpc backends
**Is your feature request related to a problem? Please describe.**
Python requirements my be conflicting 

**Describe the solution you'd like**
Create a separate conda environment for each backend and use a customized entrypoint.

**Describe alternatives you've considered**
Just rely on external

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mudler**
**Description**

This PR fixes #1117 

@Aisuko this is a PR to master with the feat/conda branch

### CODE REVIEW

**Comment by mudler** [comment]
@Aisuko https://github.com/go-skynet/LocalAI/pull/1144/commits/fbbd2f6a35734d9e40d289fcfdfdbc2db42e2771 is what I was refering to for entrypoints/makefile. in this way bark and autogptq are wired up in the container

**Comment by Aisuko** [comment]
> @Aisuko [fbbd2f6](https://github.com/go-skynet/LocalAI/commit/fbbd2f6a35734d9e40d289fcfdfdbc2db42e2771) is what I was refering to for entrypoints/makefile. in this way bark and autogptq are wired up in the container

Thank you. I have been created a new PR and included these files you mentioned  on `feat/conda` branch.

**Comment by mudler** [comment]
as soon as I get unstuck with #1154 I'll try to help you here to get this branch green

**Comment by mudler** [comment]
@Aisuko I think I'm almost there to have everything tied together within the tests too - It's just about the single backends now (for instance exllama, and Vall-E-X) to be fixed, but generally speaking we should be good to go and keep fixing on master

As soon as CI is green will merge in

**Comment by mudler** [comment]
Nice contribution @Aisuko ! merging in now to unblock other stories. I think there are still some issues to fix around vllm and Vall-E-X but can be done with this merged in master, much easier to work on.

**Pull request merged**
