### PR TITLE
update whisper_cpp with CUBLAS, HIPBLAS, METAL, OPENBLAS, CLBLAST support

### PR DESCRIPTION
**Pull request by wuxxin**
**Description**

This PR updates whisper_cpp to release 1.5 and adds GPU Support

i build and tested ROCM/HIPBLAS GPU support for whisper.
i did not test any other combination.
This is a draft. Please ignore if not fitting.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by wuxxin** [comment]
disabled WHISPER_METAL gpu acceleration, to make it work as before on metal, not causing regression. if build-apple works i would open a feature parity issue for whisper.cpp GPU on METAL support as reminder, but whisper.cpp would be up2date and gained GPU accel on CUDA, HIP

**Comment by wuxxin** [comment]
tests-apple fail with:
```
ld: warning: -no_pie is deprecated when targeting new OS versions
Undefined symbols for architecture x86_64:
  "_MTLCopyAllDevices", referenced from:
      _ggml_metal_init in libwhisper.a(ggml-metal.o)
  "_MTLCreateSystemDefaultDevice", referenced from:
      _ggml_metal_init in libwhisper.a(ggml-metal.o)
  "_OBJC_CLASS_$_MTLComputePassDescriptor", referenced from:
      objc-class-ref in libwhisper.a(ggml-metal.o)
  "_OBJC_CLASS_$_NSBundle", referenced from:
      objc-class-ref in libwhisper.a(ggml-metal.o)
  "_OBJC_CLASS_$_NSProcessInfo", referenced from:
      objc-class-ref in libwhisper.a(ggml-metal.o)
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in libwhisper.a(ggml-metal.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by mudler** [comment]
thanks @wuxxin - this is looking good from my side - let's wait for upstream and merge it once the CI is green

**Review by mudler — APPROVED** [review]

**Comment by wuxxin** [comment]
pr https://github.com/ggerganov/whisper.cpp/pull/1530 has been merged, commit hash updated to 1.15.1

**Review by mudler — APPROVED** [review]

**Comment by mudler** [comment]
mm seems it still fails @wuxxin

**Comment by wuxxin** [comment]
:+1:

**Pull request merged**
