### PR TITLE
feat(p2p): add support for configuration of edgevpn listen_maddrs, dht_announce_maddrs and bootstrap_peers 

### PR DESCRIPTION
**Pull request by mintyleaf**
**Description**

- Add the P2P env configuration flags of the new edgevpn@v0.28.4 features (listen and announce maddrs)   
- Add the bootstrap peer configuration flag
- Rename libp2p loglevel to the same LOCALAI_P2P_* prefix (LOCALAI_P2P_LIB_LOGLEVEL) to avoid possible confusion in conjunction with LOCALAI_P2P_LOGLEVEL flag (and possibly simplify the future factoring of this options)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Thank you @mintyleaf !

**Comment by mintyleaf** [comment]
@mudler keep in mind that edgevpn dependency needs to be updated to v0.28.4 for it to work   
I guess the builders will fail because of that

**Comment by mudler** [comment]
> @mudler keep in mind that edgevpn dependency needs to be updated to v0.28.4 for it to work I guess the builders will fail because of that
> 
> I don't get how that fancy chore workflow system works and if i can bump deps by myself Having that - i updated it and checked locally

Just pushed in the branch the bump. For future reference, the command that I had to run is: `go get github.com/mudler/edgevpn@v0.28.4`

**Review by mudler — APPROVED** [review]

**Review by mudler — APPROVED** [review]

**Comment by mintyleaf** [comment]
> `go get github.com/mudler/edgevpn@v0.28.4`

in order to build this i needed to do   
```
go get github.com/mudler/edgevpn@v0.28.4
   go get github.com/schollz/progressbar/v3@v3.14.4
   go get github.com/mudler/LocalAI/core/http
   go get github.com/mudler/LocalAI/core/gallery
```

\+ i'm aware of some fancy localai-bot deps update automatization, so i was confused and wasn't sure if it's ok to update them like manually

**Pull request merged**
